### ISSUE TITLE
CalendarApi params improvements + bugfix

### ISSUE THREAD

**Issue by ginccc** [kstateome/canvas-api#130]
Hi there!

ListCalendarEventsOptions needs to be able to set "type", currently this is not possible, therefore only events can be fetched, no assignments.

Also, i assume these items should be end_date, not start_date.
```
public ListCalendarEventsOptions endDate(LocalDate endDate) {
        addSingleItem("start_date", DateTimeFormatter.ISO_LOCAL_DATE.format(endDate));
        return this;
    }

    public ListCalendarEventsOptions endDate(TemporalAccessor endDate) {
        addSingleItem("start_date", DateTimeFormatter.ISO_INSTANT.format(endDate));
        return this;
    }
```

**Comment by ToeBee** [comment]
These changes have been released. Thanks for reporting the issue!
