### ISSUE TITLE
Models use Integers instead of Longs

### ISSUE THREAD

**Issue by cdonnelly1992** [kstateome/canvas-api#134]
Hey,

I have a set of users who are running into an interesting error when trying to communicate with their canvas institution.
`com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 5000000000 at line 1 column 507 path $[0].storage_quota_mb`

From the looks of things in the source code a bunch of models use Integer which in Java is a 32 bit number while according to the canvas docs all of their integers are 64 bit. 

I would think you would want to change basically all of your Integers in the models to Longs

Canvas api: https://canvas.instructure.com/doc/api/index.html
Right under "Schema" says "All integer ids in Canvas are 64 bit integers. String ids are also used in Canvas."

**Comment by ToeBee** [comment]
Well, you took care of this issue yourself! And it is released as v2.0.0. Thanks for the contribution!
