### ISSUE TITLE
Request for new release version

### ISSUE THREAD

**Issue by raistlinxw** [kstateome/canvas-api#139]
The 1.0.24 release is nearing 18 months old, and there are a number of updates that have been committed that I would like to incorporate into my local projects.   

Is it possible to request a new release that incorporates these changes?   

Thanks for your consideration.

**Comment by ToeBee** [comment]
Yeah, sorry for how long it has taken but I have now done two releases! Unfortunately version 2.0.0 breaks everything (changing Integer to Long everywhere)
